In [1]:
import numpy as np

## Numpy array

Numpy array je vícerozměrná datová struktura. Je homogení - prvky jsou vždy jednoho typu. Zpravidla čísla.

In [2]:
a = np.array([1, 2, 3])  
print(type(a))           
print(a.shape)           
print(a.ndim)
print(a.data)
print(a.dtype)
print(a.itemsize)

<class 'numpy.ndarray'>
(3,)
1
int64
8


Pole má celočíselné indexy

In [3]:
a[1]

2

Prvek můžeme měnit. Pokud zadáme jiný typ, než má již vytvořené pole, dojde k přetypování vkládaného prvku.

In [4]:
a[0] = 5.0                 
print(a)                 

[5 2 3]


Naopak při vytváření nového pole má prioritu "silnější" typ - zde float64. Pole můžeme rovnou vytvořit jako vícerozměrné.

In [5]:
b = np.array([[1,2,3],[4,5,6.0]])

In [6]:
b.shape

(2, 3)

In [7]:
b.dtype

dtype('float64')

Datový typ pro prvky ale můžeme při vytváření také přímo určit.

In [8]:
c = np.array([[1,2,3],[4,5,6.0]], dtype='complex')

In [9]:
c

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

Shape - tedy tvar pole je v podstatě jen pohledem na data. Pomocí metody reshape ho můžeme libovolně měnit. A i když pohled může mít různé rozměry data v paměti jsou stále uložena jako jednorozměrná sekvence. 

In [10]:
b.shape

(2, 3)

In [11]:
b.reshape(1, 6)

array([[1., 2., 3., 4., 5., 6.]])

In [12]:
B = b.reshape(3, 2)
B

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

**Transpozice** samozřejmě nechybí.

In [13]:
B.T

array([[1., 3., 5.],
       [2., 4., 6.]])

Numpy má řadu užitečných metod pro vytváření nových polí.

In [14]:
np.zeros(B.shape)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.full((2,2), 7) 

array([[7, 7],
       [7, 7]])

In [18]:
np.random.random((3,3))

array([[0.19815005, 0.57618777, 0.24555063],
       [0.99332544, 0.98336852, 0.99219544],
       [0.47111495, 0.82270464, 0.61740704]])

Pro generování sekvencí slouží arange či linspace.

In [19]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [20]:
np.arange( 10, 30, 0.5 )

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5,
       21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. ,
       26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5])

Linspace umožňuje určit kolik čísel v daném intervalu chceme. To je potřeba protože díky tomu jak je float uložen v paměti nejde obecně přesně určit kolik prvků arange vygeneruje.

In [21]:
np.linspace( 0, 2, 9 ) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

**Generovací funkce a metody:** array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, numpy.random.rand, numpy.random.randn, fromfunction, fromfile

## Výpočty pomocí Array

Naprostá většina operací je automaticky "po prvcích". Což platí jak pro početní operace tak pro funkce, které numpy nabízí.

In [22]:
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
b-2

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [24]:
bb = b.reshape(1,6)

In [25]:
bb

array([[1., 2., 3., 4., 5., 6.]])

In [26]:
bb-np.arange(6)

array([[1., 1., 1., 1., 1., 1.]])

In [27]:
bb*3

array([[ 3.,  6.,  9., 12., 15., 18.]])

In [28]:
np.sin(bb)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ]])

In [29]:
np.exp(bb)

array([[  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 , 403.42879349]])

## Maticové počítání

In [30]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [31]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [32]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [33]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [34]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [35]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [36]:
np.divide(y, x)

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [37]:
np.sqrt(y)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [38]:
np.exp(y)

array([[ 148.4131591 ,  403.42879349],
       [1096.63315843, 2980.95798704]])

In [39]:
np.log(y)

array([[1.60943791, 1.79175947],
       [1.94591015, 2.07944154]])

## Skalární součin

In [40]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [41]:
v.dot(w)

219

In [42]:
np.dot(v, w)

219

In [43]:
np.dot(X, v)

array([29, 67])

Od Pythonu 3.5 dále jde skalární součin zapsat i pomocí @

In [44]:
X @ Y

array([[19, 22],
       [43, 50]])

In [45]:
X.dot(Y)

array([[19, 22],
       [43, 50]])

In [46]:
v @ w

219

## Indexování 

In [47]:
i1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [48]:
i1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Slice index

Pro 1D pole se chová tak jako pro list

In [49]:
i2 = i1.reshape(12,)
i2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
i2[2:8]

array([3, 4, 5, 6, 7, 8])

In [51]:
i2[2:8:2]

array([3, 5, 7])

2D pole (matice) má index pro každou osu zvlášť.

Všechny řádky ve druhém sloupci

In [52]:
i1[:, 1]

array([ 2,  6, 10])

První dva řádky ve druhém a třetím sloupci

In [53]:
i1[:2, 1:3]

array([[2, 3],
       [6, 7]])

Všechny řádky, od druhého sloupce dále (třetí, čtvrtý atd..)

In [54]:
i1[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

### Integer indexing

Z numpy array můžeme selektovat prvky dle konkrétních potřeb.

In [55]:
A1 = np.array([[1,2], [3, 4], [5, 6]])
A1

array([[1, 2],
       [3, 4],
       [5, 6]])

Zápis A1[[0, 1, 2], [0, 1, 0]] vybere první prvek z prvního, druhý prvek z druhého a první prvek z třetího řádku matice.

In [56]:
A1[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

Je to přehlednější a ekvivaelntní zápis k:

In [57]:
np.array([A1[0, 0], A1[1, 1], A1[2, 0]])

array([1, 4, 5])

### Boolean array indexing

In [58]:
A2 = np.arange(1, 7).reshape((3,2))
A2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
bool_idx = A2 > 2

In [60]:
bool_idx 

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [61]:
A2[bool_idx]

array([3, 4, 5, 6])

## Broadcasting

### For cyklus

In [62]:
XX = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
vv = np.array([1, 0, 1])
YY = np.empty_like(XX)   # prázdná matice stejná jako X

# Ke každému řádku X přičteme v 
for i in range(4):
    YY[i, :] = XX[i, :] + vv

print(YY)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Vektorizace

In [63]:

M = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
n = np.array([1, 0, 1])
o = np.tile(vv, (4, 1))   # doslova vydláždí nový vektor tvaru 4,1 tím původním v
print("vektor 0:", o)
N = M + vv  # sečteme jako vektory
print("matice N:", N)

vektor 0: [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
matice N: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


 ### Broadcast
 
 Vektorizuje automaticky.

In [64]:
M2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(M.shape)
v2 = np.array([1, 2, 3])
print(v.shape)
N2 = M2 + v2  # součet využije broadcasting
print(N2) 

(4, 3)
(2,)
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


Broadcasting se chová, jako by vektor v měl stejný tvar jako matice X (4,3), nikoliv (3,)

Vektory musí být tvarově **kompatibilní**. Což znamená, že pro příslušnou osu, mají buď stejný počet prvků (shape)  nebo jedničku.


In [65]:
W1 = np.ones((2,2))

In [66]:
W1

array([[1., 1.],
       [1., 1.]])

In [67]:
x3 = np.arange(4)
y3 = np.arange(6)

In [68]:
x3.shape

(4,)

In [69]:
y3.shape

(6,)

Pokus o sečtení x3 + y3 vyvolá ValueError

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-387-bab4e9e8b45d> in <module>
----> 1 x3 + y3

ValueError: operands could not be broadcast together with shapes (4,) (6,) 
```    

In [70]:
# x3 + y3

In [71]:
x4 = x3.reshape(4,1)

In [72]:
x4 + y3

array([[0, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8]])